server:
  port: 8082

logging:
  level:
    root: info
    org.springframework.web: info
    top.shmilyqjj.springboot.controller: debug
    top.shmilyqjj.springboot.controller.channel: debug
spring:
  mvc:
    converters:
      preferred-json-mapper: gson
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  typeAliasesPackage: top.shmilyqjj.springboot.models
  mapperLocations: classpath:mapper/*.xml